name: OKX MACD Opportunity Scanner

on:
  # 1. 定时触发：使用CRON表达式
  # '45 * * * *' -> 在每个小时的第45分钟运行一次。
  # 这样可以在小时K线收盘前及时发现机会。
  schedule:
    - cron: '45 * * * *'

  # 2. 手动触发：允许你在GitHub Actions页面点击按钮手动运行
  workflow_dispatch:

jobs:
  scan-opportunities:
    runs-on: ubuntu-latest

    steps:
      # 第一步：检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 第二步：设置Python环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 第三步：安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 第四步：运行监控脚本
      - name: Run OKX Monitor Script
        env:
          SERVER_JIANG_KEY: ${{ secrets.SERVER_JIANG_KEY }}
        run: python 14d.py
