name: Crypto Volume Alert

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai
  NODE_ENV: production

jobs:
  monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: |
          npm ci
          echo "Lockfile verification:"
          ls -la node_modules/
          npm list --depth=0

      - name: Run Single Pair Monitor
        run: npm start

      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ github.run_number }}
          path: |
            *.log
            logs/
          retention-days: 3
