name: Binance Volume Alert

on:
  schedule:
    - cron: '5 * * * *' # 每小时的第5分钟运行
  workflow_dispatch: # 允许手动触发

jobs:
  run_alert_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-binance pandas requests

      - name: Run Binance Volume Alert Script
        env:
          # BINANCE_API_KEY 和 BINANCE_API_SECRET 已移除
          SERVERCHAN_SENDKEY: ${{ secrets.SERVERCHAN_SENDKEY }}
        run: python binance_volume_alert.py
