name: 全交易对爆量监控
on:
  schedule:
    - cron: "*/15 * * * *"  # 每15分钟运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install axios
      - name: 运行监控
        run: node monitor-all-pairs.js
      - name: 显示时间
        run: date
