name: 全交易对爆量监控(轮询模式)
on:
  schedule:
    - cron: "*/15 * * * *"  # 每15分钟运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # 恢复状态文件
      - name: 恢复状态
        uses: actions/download-artifact@v3
        with:
          name: monitor-state
          path: ./
          
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - run: npm install axios
      
      - name: 运行监控
        run: node monitor-all-pairs.js
        
      # 保存状态文件
      - name: 保存状态
        uses: actions/upload-artifact@v3
        with:
          name: monitor-state
          path: monitor-state.json
          retention-days: 1
          
      - name: 显示时间
        run: date
