name: 全交易对爆量监控(轮询模式)
on:
  schedule:
    - cron: "*/15 * * * *"  # 每15分钟运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # 恢复状态文件（仅在非首次运行时下载）
      - name: 下载状态文件
        uses: actions/download-artifact@v3
        with:
          name: monitor-state
          path: ./
        continue-on-error: true  # 允许首次运行时没有状态文件
          
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - run: npm install axios
      
      - name: 运行监控
        run: node monitor-all-pairs-rotating.js
        
      # 保存状态文件
      - name: 上传状态文件
        uses: actions/upload-artifact@v3
        with:
          name: monitor-state
          path: monitor-state.json
          retention-days: 1  # 只保留一天的状态文件
          
      - name: 显示时间
        run: date
