name: OKX Volume Monitor

on:
  schedule:
    # 每30分钟运行一次
    - cron: '*/30 * * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-matplotlib
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas numpy aiohttp matplotlib
        
    - name: Run volume monitor
      run: python monitor.py
      env:
        SERVER_JIANG_KEY: SCT281228TBF1BQU3KUJ4vLRkykhzIE80e
        MPLBACKEND: Agg  # 设置matplotlib使用非交互式后端
