name: 全交易对爆量监控(轮询模式)
on:
  schedule:
    - cron: "*/15 * * * *"  # 每15分钟运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # 使用缓存恢复状态文件
      - name: 恢复状态缓存
        id: cache-state
        uses: actions/cache@v3
        with:
          path: monitor-state.json
          key: monitor-state-${{ github.run_id }}
          restore-keys: |
            monitor-state-
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - run: npm install axios
      
      - name: 运行监控
        run: node monitor-all-pairs-rotating.js
        
      # 保存状态到缓存
      - name: 保存状态缓存
        uses: actions/cache@v3
        with:
          path: monitor-state.json
          key: monitor-state-${{ github.run_id }}
          restore-keys: |
            monitor-state-
          
      - name: 显示时间
        run: date
